config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
]

core/urls.py
from django.urls import path
from .views import player_overview, match_list, match_detail

urlpatterns = [
    path("players/", player_overview),
    path("matches/", match_list),
    path("matches/<int:match_id>/", match_detail),
]

core/models.py
from django.db import models

# Create your models here.


class Team(models.Model):
    name = models.CharField(max_length=100)
    region = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Player(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    summoner_name = models.CharField(max_length=100)
    role = models.CharField(max_length=50)

    def __str__(self):
        return self.summoner_name


class Match(models.Model):
    external_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    patch = models.CharField(max_length=20)
    played_at = models.DateTimeField()
    duration_minutes = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.external_id} (Patch {self.patch})"


class PlayerMatchStats(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)

    champion = models.CharField(max_length=50)

    kills = models.IntegerField()
    deaths = models.IntegerField()
    assists = models.IntegerField()

    cs = models.IntegerField(null=True, blank=True)
    gold = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.player} in match {self.match}"


class ObjectiveEvent(models.Model):
    OBJECTIVE_CHOICES = [
        ("dragon", "Dragon"),
        ("baron", "Baron"),
        ("tower", "Tower"),
        ("grubs", "Void Grubs"),
        ("herald", "Herald"),
    ]

    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    objective_type = models.CharField(
        max_length=20,
        choices=OBJECTIVE_CHOICES
    )

    minute = models.IntegerField()
    timestamp_seconds = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.objective_type} at {self.minute} min"


class Vod(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    provider = models.CharField(max_length=50)
    url = models.URLField()

    game_start_offset_seconds = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.provider} VOD for match {self.match_id}"

class TeamMatchSummary(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    side = models.CharField(max_length=10)

    bans_1 = models.CharField(max_length=50, blank=True, default="")
    bans_2 = models.CharField(max_length=50, blank=True, default="")
    bans_3 = models.CharField(max_length=50, blank=True, default="")
    bans_4 = models.CharField(max_length=50, blank=True, default="")
    bans_5 = models.CharField(max_length=50, blank=True, default="")

    gold_k = models.FloatField(null=True, blank=True)
    team_kills = models.IntegerField(null=True, blank=True)
    towers = models.IntegerField(null=True, blank=True)

    objectives_shorthand = models.CharField(max_length=200, blank=True, default="")

    def __str__(self):
        return f"{self.team.name} ({self.side}) summary for match {self.match_id}"

core/views.py
from django.shortcuts import render
from .models import Player, PlayerMatchStats, Match, ObjectiveEvent, Vod, TeamMatchSummary
from django.db.models import Avg


def player_overview(request):
    players = Player.objects.all()

    data = []
    for player in players:
        avg_gold = PlayerMatchStats.objects.filter(
            player=player
        ).aggregate(Avg("gold"))["gold__avg"]

        data.append({
            "player": player,
            "avg_gold": avg_gold,
        })

        return render(request, "player_overview.html", {
            "data": data
        })


def match_list(request):
    matches = Match.objects.all().order_by("-played_at")

    return render(request, "match_list.html", {
        "matches": matches
    })


def match_detail(request, match_id):
    match = Match.objects.get(id=match_id)

    stats = PlayerMatchStats.objects.filter(match=match)

    from collections import defaultdict

    roles_order = ["TOP", "JNG", "MID", "BOT", "SUP"]

    team_players = defaultdict(dict)

    for s in stats:
        role = s.player.role.upper()
        team_name = s.player.team.name
        team_players[team_name][role] = s

    team_totals = {}

    for team_name, role_map in team_players.items():
        kills = sum(p.kills for p in role_map.values())
        deaths = sum(p.deaths for p in role_map.values())
        assists = sum(p.assists for p in role_map.values())

        team_totals[team_name] = f"{kills}-{deaths}-{assists}"

    teams = list(team_players.keys())
    if len(teams) == 2:
        team_left = teams[0]
        team_right = teams[1]
    else:
        team_left = team_right = None

    paired_rows = []

    if team_left and team_right:
        for role in roles_order:
            left = team_players[team_left].get(role)
            right = team_players[team_right].get(role)

            paired_rows.append({
                "role": role,
                "left": left,
                "right": right,
            })

    objectives = ObjectiveEvent.objects.filter(match=match).order_by("minute")
    vod = Vod.objects.filter(match=match).first()
    team_summaries = TeamMatchSummary.objects.filter(match=match)

    objective_rows = []
    for obj in objectives:
        computed = None
        if vod:
            computed = vod.game_start_offset_seconds + (obj.minute * 60)

        jump_seconds = obj.timestamp_seconds if obj.timestamp_seconds else computed

        objective_rows.append({
            "obj": obj,
            "jump_seconds": jump_seconds,
        })
    return render(request, "match_detail.html", {
        "match": match,
        "stats": stats,
        "vod": vod,
        "objective_rows": objective_rows,
        "team_summaries": team_summaries,
        "paired_rows": paired_rows,
        "team_totals": team_totals,
        "team_left": team_left,
        "team_right": team_right,
    })

core/templates/match_detail.html
{% load replace_filters %}

<!doctype html>
<html>
  <head>
    <title>Match Detail</title>
  </head>
  <body>
    <h1>Match Detail</h1>

    <h2> {{ match.external_id|underscore_to_space }}

    <p>
      Patch {{ match.patch }}<br />
      Played at {{ match.played_at }}
    </p>

    <h2>VOD</h2>
    {% if vod %}
    <p>
      <a href="{{ vod.url }}" target="_blank">Open {{ vod.provider }} VOD</a>
    </p>
    {% else %}
    <p>No VOD added yet.</p>
    {% endif %}

    <h2>Team Summary</h2>

    {% if team_summaries %}
    <table border="1">
      <tr>
        <th>Team</th>
        <th>Side</th>
        <th>Bans</th>
        <th>Gold (k)</th>
        <th>Kills</th>
        <th>Towers</th>
        <th>Objectives</th>
      </tr>
      {% for s in team_summaries %}
      <tr>
        <td>{{ s.team.name }}</td>
        <td>{{ s.side }}</td>
        <td>
          {{ s.bans_1 }}, {{ s.bans_2 }}, {{ s.bans_3 }}, {{ s.bans_4 }}, {{s.bans_5 }}
        </td>
        <td>{{ s.gold_k }}</td>
        <td>{{ s.team_kills }}</td>
        <td>{{ s.towers }}</td>
        <td>{{ s.objectives_shorthand }}</td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
    <p>No team summary data yet.</p>
    {% endif %}

    <h2>Player Matchup</h2>

    {% if team_left and team_right %}
    <h3>
      {{ team_left }} {{ team_totals.team_left }} vs {{ team_totals.team_right }} {{ team_right }}
    </h3>

    <table border="1">
      <tr>
        <th>{{ team_left }}</th>
        <th>K-D-A</th>
        <th>CS</th>
        <th>Gold</th>
        <th>Role</th>
        <th>Gold</th>
        <th>CS</th>
        <th>K-D-A</th>
        <th>{{ team_right }}</th>
      </tr>

      {% for row in paired_rows %}
      <tr>
        <td>
          {% if row.left %} {{ row.left.player.summoner_name }} ({{ row.left.champion }}) {% endif %}
        </td>

        <td>
          {% if row.left %} {{ row.left.kills }}-{{ row.left.deaths }}-{{ row.left.assists }} {% endif %}
        </td>

        <td>
          {% if row.left %} {{ row.left.cs }} {% endif %}
        </td>

        <td>
          {% if row.left %} {{ row.left.gold }} {% endif %}
        </td>

        <td>{{ row.role }}</td>

        <td>
          {% if row.right %} {{ row.right.gold }} {% endif %}
        </td>

        <td>
          {% if row.right %} {{ row.right.cs }} {% endif %}
        </td>

        <td>
          {% if row.right %} {{ row.right.kills }}-{{ row.right.deaths }}-{{ row.right.assists }} {% endif %}
        </td>

        <td>
          {% if row.right %} {{ row.right.player.summoner_name }} ({{ row.right.champion }}) {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
    {% endif %}

    <h2>Objectives</h2>
    <ul>
      {% for row in objective_rows %}
      <li>
        {{ row.obj.minute }} min — {{ row.obj.team.name }} took {{
        row.obj.get_objective_type_display }} {% if vod and row.jump_seconds %}
        —
        <a href="{{ vod.url }}?t={{ row.jump_seconds }}" target="_blank">jump</a
        >{% endif %}
      </li>
      {% endfor %}
    </ul>
  </body>
</html>

core/templates/match_list.html
{% load replace_filters %}

<!DOCTYPE html>
<html>
  <head>
    <title>Matches</title>
  </head>
  <body>
    <h1>Matches</h1>

    <ul>
      {% for match in matches %}
        <li>
          <a href="/matches/{{ match.id }}">
            {{ match.external_id|underscore_to_space }} - {{ match.played_at }}
        </li>
      {% endfor %}
    </ul>
  </body>
</html>

core/templates/player_overview.html
<!doctype html>
<html>
  <head>
    <title>Player Overview</title>
  </head>
  <body>
    <h1>Player Overview</h1>

    <ul>
      {% for row in data %}
      <li>{{ row.player.summoner_name }} - Average Gold: {{ row.avg_gold }}</li>
      {% endfor %}
    </ul>
  </body>
</html>